# name: Run Every 15 minutes

# on:
#   schedule:
#     - cron: '*/15 * * * *'
#   workfloow_dispatch:

# jobs:
#   run-script:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout repo
#       uses: actions/checkout@v3

#     - name: set up pyhton
#       uses: actions/setup-pyhton@v4
#       with:
#         python-version: '3.10'

#     - name: Run script
#       run: python script.py


name: Daily Python Script

on:
  schedule:
    - cron: "*/16 * * * *"  # Every day at 8:00 UTC

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run script
        run: python script.py
